spring:
  application:
    name: animal-demo

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database
    username: user
    password: password

logging:
  level:
    org:
      springframework:
        jdbc: INFO
